services:
  shadowtrap:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    ports:
      - "22:2222"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - shadowtrap
